# Generated by Django 5.2.1 on 2025-06-04 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centros_deportivos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='centrodeportivo',
            name='id',
        ),
        migrations.AddField(
            model_name='centrodeportivo',
            name='id_centro',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='centrodeportivo',
            table='CentroDeportivo',
        ),
        migrations.CreateModel(
            name='Cancha',
            fields=[
                ('id_cancha', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.IntegerField()),
                ('tipo', models.CharField(choices=[('FUTBOL', 'Fútbol'), ('TENIS', 'Tenis'), ('BALONCESTO', 'Baloncesto'), ('PADEL', 'Pádel'), ('VOLEIBOL', 'Voleibol')], max_length=50)),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('OCUPADA', 'Ocupada'), ('MANTENIMIENTO', 'En Mantenimiento'), ('INACTIVA', 'Inactiva')], default='DISPONIBLE', max_length=50)),
                ('id_centro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canchas', to='centros_deportivos.centrodeportivo')),
            ],
            options={
                'verbose_name': 'Cancha',
                'verbose_name_plural': 'Canchas',
                'db_table': 'Cancha',
            },
        ),
    ]
