# Generated by Django 5.2.1 on 2025-06-04 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centros_deportivos', '0002_remove_centrodeportivo_id_centrodeportivo_id_centro_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id_evento', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_evento', models.CharField(choices=[('TORNEO', 'Torneo'), ('CLASE', 'Clase'), ('PARTIDO', 'Partido Abierto'), ('MANTENIMIENTO', 'Mantenimiento')], max_length=50)),
                ('nombre', models.CharField(max_length=255)),
                ('hora', models.TimeField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('CANCELADO', 'Cancelado'), ('FINALIZADO', 'Finalizado'), ('PROXIMO', 'Próximo')], default='PROXIMO', max_length=50)),
                ('id_centro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='centros_deportivos.centrodeportivo')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'db_table': 'Evento',
            },
        ),
    ]
