# Generated by Django 5.2.1 on 2025-06-18 08:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centros_deportivos', '0003_evento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='centrodeportivo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='centrodeportivo',
            name='propietario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='centros_propietario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='centrodeportivo',
            name='rut',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
