# Generated by Django 5.2.1 on 2025-06-04 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('centros_deportivos', '0003_evento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('id_suscripcion', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_plan', models.CharField(choices=[('BASICO', 'Básico'), ('PREMIUM', 'Premium'), ('EMPRESARIAL', 'Empresarial')], max_length=50)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('INACTIVA', 'Inactiva'), ('PENDIENTE', 'Pendiente'), ('CANCELADA', 'Cancelada')], default='ACTIVA', max_length=50)),
                ('id_centro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suscripciones', to='centros_deportivos.centrodeportivo')),
            ],
            options={
                'verbose_name': 'Suscripción',
                'verbose_name_plural': 'Suscripciones',
                'db_table': 'Suscripcion',
            },
        ),
    ]
