# Generated by Django 5.2.1 on 2025-06-04 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('centros_deportivos', '0003_evento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('precio', models.FloatField()),
                ('stock', models.IntegerField()),
                ('id_centro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='centros_deportivos.centrodeportivo')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'Producto',
            },
        ),
    ]
