# Generated by Django 5.2.1 on 2025-06-04 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id_pago', models.AutoField(primary_key=True, serialize=False)),
                ('metodo', models.CharField(choices=[('TARJETA_CREDITO', 'Tarjeta de Crédito'), ('TARJETA_DEBITO', 'Tarjeta de Débito'), ('PAYPAL', 'PayPal'), ('TRANSFERENCIA_BANCARIA', 'Transferencia Bancaria'), ('EFECTIVO', 'Efectivo')], max_length=50)),
                ('monto', models.FloatField()),
                ('fecha', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'db_table': 'Pago',
                'ordering': ['-fecha'],
            },
        ),
    ]
